### PR TITLE
A working markdown XBlock

### PR DESCRIPTION
**Pull request by arbrandes**

### CODE REVIEW

**Comment by fghaas** [comment]
OK, so that all looks good functionally. About the naming: I take it
no-one thought to devise a proper module namespace when they came up
with the XBlock concept, correct? So the XBlock modules are all actually
expected to be named "foobar", rather than something like
"edx.xblock.foobar" — which is begging for naming conflicts with
existing Python modules?

**Comment by arbrandes** [comment]
Correct, as far as I can tell from all XBlocks I've seen, and from the docs.  No namespacing whatsoever, which sucks bigtime.

**Comment by fghaas** [comment]
Where's my surprised face?

**Comment by fghaas** [comment]
Wasn't there still some renaming of `markdown` to `mdown` pending in some of the CSS?

**Comment by arbrandes** [comment]
You mean this?

https://github.com/hastexo/markdown-xblock/blob/master/mdown/templates/main.html#L1

Sure, I can change that to "mdown_block".

**Comment by fghaas** [comment]
Yes, that one.

**Comment by arbrandes** [comment]
@fghaas, addressed on ac5983c.

**Pull request merged**
